//auth action types
export const START_AUTH = "START_AUTH";
export const SUCCESS_AUTH = "SUCCESS";
export const SUCCESS_UPLOAD = "SUCCESS_UPLOAD";
export const FAIL_AUTH = "FAIL_AUTH";
export const LOGOUT_AUTH = "LOGOUT_AUTH";
export const SET_LOGGED_USER = "SET_LOGGED_USER";
export const SET_LOGGED_USER_REQUEST = "SET_LOGGED_USER_REQUEST";
export const SET_LOGGED_USER_SUCCESS = "SET_LOGGED_USER_SUCCESS";
export const SET_FOLLOWERS_LIST_REQUEST = "SET_FOLLOWERS_LIST_REQUEST";
export const SET_FOLLOWERS_LIST_SUCCESS = "SET_FOLLOWERS_LIST_SUCCESS";
export const SET_FOLLOWING_LIST_REQUEST = "SET_FOLLOWING_LIST_REQUEST";
export const SET_FOLLOWING_LIST_SUCCESS = "SET_FOLLOWING_LIST_SUCCESS";
export const SET_LOGGED_OUT_USER = "SET_LOGGED_OUT_USER";

//user action types
export const SET_CURRENT_USER = "SET_CURRENT_USER";
export const UPDATE_CURRENT_USER = "UPDATE_CURRENT_USER";
export const UPDATE_CURRENT_USER_SUCCESS = "UPDATE_CURRENT_USER_SUCCESS";
export const GET_PROFILE = "GET_PROFILE";
export const PROFILE_LOADING = "PROFILE_LOADING";
export const PROFILE_NOT_FOUND = "PROFILE_NOT_FOUND";
export const CLEAR_CURRENT_PROFILE = "CLEAR_CURRENT_PROFILE";

export const CLEAR_ERRORS = "CLEAR_ERRORS";
export const GET_ERRORS = "GET_ERRORS";

//POST acction types
export const GET_POSTS_REQUEST = "GET_POSTS_REQUEST";
export const GET_POSTS_SUCCESS = "GET_POSTS_SUCCESS";
export const GET_SELECTED_FEED_POSTS_REQUEST =
  "GET_SELECTED_FEED_POSTS_REQUEST";
export const GET_SELECTED_FEED_POSTS_SUCCESS =
  "GET_SELECTED_FEED_POSTS_SUCCESS";
export const GET_SELECTED_POST_REQUEST = "GET_SELECTED_POST_REQUEST";
export const GET_SELECTED_POST_SUCCESS = "GET_SELECTED_POST_SUCCESS";
export const ADD_POST_REQUEST = "ADD_POST_REQUEST";
export const ADD_POST_SUCCESS = "ADD_POST_SUCCESS";
export const DELETE_POST = "DELETE_POST";
export const ADD_LIKE_POST_REQUEST = "ADD_LIKE_POST_REQUEST";
export const ADD_LIKE_POST_SUCCESS = "ADD_LIKE_POST_SUCCESS";
export const REMOVE_LIKE_POST_REQUEST = "REMOVE_LIKE_POST_REQUEST";
export const REMOVE_LIKE_POST_SUCCESS = "REMOVE_LIKE_POST_SUCCESS";

// //Search action Types
export const GET_USERS = "GET_USERS";
export const FAIL_GET_USERS = "FAIL_GET_USERS";
export const GET_SEARCHED_USER = "GET_SEARCHED_USER";
export const SET_SEARCHED_USER = "SET_SEARCHED_USER";
export const FILTER_USERS = "FILTER_USERS";
export const LOADING_USERS = "LOADING_USERS";
